CREATE BIGFILE TABLESPACE TSMUXDB 
    DATAFILE 
        'FS_TSMUXDB' SIZE 734003200 
    BLOCKSIZE 8192 
    
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT MANUAL 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
