-- USER SQL
CREATE USER "HARRY" IDENTIFIED BY "123456"  
DEFAULT TABLESPACE "TSMUXDB"
ENABLE EDITIONS ;

-- QUOTAS
ALTER USER "HARRY" QUOTA UNLIMITED ON "TSMUXDB";

-- ROLES
GRANT "DBA" TO "HARRY" WITH ADMIN OPTION;
GRANT "ROL_API" TO "HARRY" WITH ADMIN OPTION;
GRANT "CONNECT" TO "HARRY" WITH ADMIN OPTION;
ALTER USER "HARRY" DEFAULT ROLE "DBA","ROL_API","CONNECT";

-- SYSTEM PRIVILEGES

